### ISSUE TITLE
send_cmd_help support for help.py

### ISSUE THREAD

**Issue by Isaiahfeldt** [SirThane/SESTREN#3]
Many of my cogs include subcommands and utilize:
>if ctx.invoked_subcommand is None:
                     await send_cmd_help(ctx)

Though your embed help system seems to be conflicting with it.

> [17/09/2017 17:59] ERROR red on_command_error 369: Exception in command 'audioset'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Administrator\Documents\Servers\xampp\htdocs\Bell Instances\Bellbot\cogs\audio.py", line 1051, in audioset
    await send_cmd_help(ctx)
  File "red.py", line 140, in send_cmd_help
    for page in pages:
TypeError: 'coroutine' object is not iterable
C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\asyncio\events.py:127: RuntimeWarning: coroutine 'Help.format_help_for' was never awaited
  self._callback(*self._args)

Should I be replacing await send_cmd_help(ctx) in each of my cogs with something else to support help.py or is this an error on your part?

Thanks!

**Comment by SirThane** [comment]
Old issue. Deprecated module. Completely rewritten in d.py 1.6.0 with discord-ext-menus
